#ifndef CONFIG_HPP
#define CONFIG_HPP

#include <cstddef>
#include <string>

inline int sample_width = 64;
inline int sample_height = 64;
// CLIP hidden sizes are fixed: 768 for SD1.5 / SDXL encoder 1 (CLIP-L),
// 1280 for SDXL encoder 2 (CLIP-G).
inline constexpr int text_embedding_size = 768;
inline constexpr int text_embedding_size_2 = 1280;
inline int output_width = 512;
inline int output_height = 512;

// ---- Anima (DiT + Qwen) constants ------------------------------------------
// Anima latents are 16-channel (Wan 2.1 / Qwen-Image VAE) instead of SD's 4.
inline constexpr int anima_latent_channels = 16;
// Qwen3-0.6B text encoder: 512-token input, 1024-dim hidden states (no pooled
// output, no learned positional table — RoPE is internal to the model). The
// merged text encoder (Qwen + LLM adapter) re-grids onto the T5 token sequence,
// so its OUTPUT context — what the UNet's encoder_hidden_states consumes — is
// also 512 long. Two distinct lengths (both 512, kept separate so the Qwen and
// T5 sides can diverge if a future export changes one):
//   anima_qwen_seq_len : qwen input_embedding + qwen_mask
//   anima_text_seq_len : t5_ids/t5_mask, clip context output,
//                        Conditioning hidden, UNet encoder_hidden_states
inline constexpr int anima_qwen_seq_len = 512;
inline constexpr int anima_text_seq_len = 512;
inline constexpr int anima_text_embedding_size = 1024;
// Wan 2.1 per-channel latent normalization (16 channels). The diffusion model
// works in the normalized space; the VAE consumes/produces the de-normalized
// latent: vae_latent = model_latent * std + mean  (process_out), and the
// inverse for encoding: model_latent = (vae_latent - mean) / std.
inline constexpr float anima_latent_mean[16] = {
    -0.7571f, -0.7089f, -0.9113f, 0.1075f,  -0.1745f, 0.9653f,
    -0.1517f, 1.5508f,  0.4134f,  -0.0715f, 0.5517f,  -0.3632f,
    -0.1922f, -0.9497f, 0.2503f,  -0.2921f};
inline constexpr float anima_latent_std[16] = {
    2.8184f, 1.4541f, 2.3275f, 2.6558f, 1.2196f, 1.7708f, 2.6052f, 2.0743f,
    3.2687f, 2.1526f, 2.8652f, 1.5579f, 1.6382f, 1.1253f, 2.8251f, 1.9160f};

// ---- Z-Image Turbo ---------------------------------------------------------
// First release is deliberately a fixed 1024px text-to-image profile. The
// Flux-derived VAE has 16 latent channels and an effective pixel scale of 8;
// ZImagePipeline doubles its latent spatial size before the 2x2 DiT patch.
inline constexpr int zimage_latent_channels = 16;
inline constexpr int zimage_canvas_size = 1024;
// ---- 多比例支持（台账 #86）----
// 🔴 这里**只放「允许的像素尺寸」**，用于挡住非法请求；
//    「哪个比例用哪个 QNN 图」的映射一律**从契约读**，不在代码里写第二份清单（#73）。
// 几何约束（由 VAE 8x 与 DiT 2x2 patch 决定）：宽高必须能被 16 整除，latent 两维为偶。
struct ZImageSize { int width; int height; };
// 🔴 几何不是随便挑的：每个尺寸都要过 spill-fill 门（part2a 的 spillFillBufferSize
//    只看 unified 长度 N，已用已知样本验证——4:3 与 3:4 同 N=4224 时逐字节相同）。
//    1152x864（N=3968）就是因为 spillFill 冲到 999 MiB 被否掉的，别再往回加。
inline constexpr ZImageSize zimage_sizes[] = {
    {1024, 1024},   // 1:1   N=4176  spillFill 276.9 MiB
    {1184,  896},   // 4:3   N=4224  spillFill 269.1 MiB（已 D1/D2 全过并真机出图）
    { 896, 1184},   // 3:4   N=4224  spillFill 269.1 MiB
    {1280,  720},   // 16:9  N=3680  spillFill 248.6 MiB
    { 720, 1280},   // 9:16  N=3680  spillFill 248.6 MiB
};
inline bool zimageSizeSupported(int w, int h) {
  for (const auto &s : zimage_sizes)
    if (s.width == w && s.height == h) return true;
  return false;
}
// 契约里 qnn_graphs 的键，形如 "1184x896"
inline std::string zimageSizeKey(int w, int h) {
  return std::to_string(w) + "x" + std::to_string(h);
}
// The delivered QNN text contexts have a fixed [1, 80] host ABI.
//   20 -> 32  (2026-08-27, ledger #134 Tier 1): text_encoder only, 22 baked shape
//             constants per segment retargeted; the transformer was left untouched
//             because its caption slot was already 32 wide.
//   32 -> 80  (2026-08-29, ledger #134 Tier 2): ALL EIGHT graphs re-cut, i.e. the
//             four transformer segments too (caption 32->80, unified 4128->4176;
//             the 4096 image tokens are untouched).
// The old comment here claimed ">32 would need re-exporting the transformer from
// PyTorch, which does not fit this host RAM".  That was WRONG on both counts and is
// kept only to explain the retraction (ledger #137): no re-export was needed at all
// (the seq dims live in graph initializers / value_info and were retargeted in
// place), so tensor names never changed and the +6.74 dB Clip+FP16 whitelist stayed
// valid -- its overrides JSON regenerated byte-identical at L=80.
// Safety was gated before any of this was built: ledger #139 re-measured every
// candidate tensor's |a|max at L=80 and found 0 new FP16 overflows in all four
// segments, plus n=59 same-caliber L=32/L=80 pairs showing sequence length does not
// move activation ranges (ratio 0.9706~1.0179).
inline constexpr int zimage_text_max_length = 80;
// Tokens the Qwen chat template itself consumes out of those 80, leaving
// 72 for the user's actual prompt (80 - 8). Counted 2026-08-26 by looking every piece
// of ZImagePrompt.hpp's template up in the delivered tokenizer.json vocab:
// <|im_start|>(151644) user(872) \n(198) ... <|im_end|>(151645) \n(198)
// <|im_start|>(151644) assistant(77091) \n(198) = 8. "userĊ"/"assistantĊ" are
// NOT in the vocab, so no merge shortens this. (A BPE merge across the
// prompt's first character could shift the effective budget by 1.)
inline constexpr int zimage_text_template_tokens = 8;
inline constexpr int zimage_text_embedding_size = 2560;
inline constexpr int zimage_turbo_steps = 8;
inline constexpr float zimage_vae_scaling_factor = 0.3611f;
inline constexpr float zimage_vae_shift_factor = 0.1159f;

#endif  // CONFIG_HPP